version: "3"

tasks:
  download-all:
    cmds:
      - go get github.com/ilyakaznacheev/cleanenv
      - go get github.com/rabbitmq/amqp091-go
      - go get github.com/go-mail/mail/v2
      - go get github.com/fatih/color
      - go get github.com/stretchr/testify