# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: online-shop
      POSTGRES_USERNAME: online-shop
      POSTGRES_DB: online-shop
